[pytest]
pythonpath = .
env =
    DATABASE_URL=postgresql+psycopg2://postgres:raman8757@localhost:5432/algo_trading
    SECRET_KEY=this_is_a_very_long_secret_key_for_testing_32chars
    JWT_SECRET_KEY=this_is_a_very_long_jwt_secret_key_for_testing_32chars
    BROKER_SECRET_KEY=kLMhmBmPStVCGWNtSl1GBOSri_sWCow3zuAbhNppJu8=
    DEBUG=True
    ZERODHA_API_KEY=test_api_key
    ZERODHA_API_SECRET=test_api_secret
    ZERODHA_REDIRECT_URL=test_redirect_url
    TESTING=True

