export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  ORDERS: '/orders',
  PORTFOLIO: '/portfolio',
  WATCHLIST: '/watchlist',
  STRATEGY: '/strategy',
  JOURNAL: '/journal',
  BROKERS: '/brokers',
  KILL_SWITCH: '/admin/kill-switch',
  ADMIN_DASHBOARD: '/admin',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '/404',
};
