"""add_broker_table

Revision ID: 712b42bcdef0
Revises: 20260807200001
Create Date: 2026-08-07 22:53:37.757182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712b42bcdef0'
down_revision: Union[str, Sequence[str], None] = '20260807200001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=255), nullable=False),
    sa.Column('broker_type', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('api_secret', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_broker_name'), 'brokers', ['broker_name'], unique=False)
    op.create_index(op.f('ix_brokers_broker_type'), 'brokers', ['broker_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brokers_broker_type'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_broker_name'), table_name='brokers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
