import axios, { AxiosInstance, InternalAxiosRequestConfig, AxiosResponse, AxiosError } from 'axios';
import { validateEnv } from '@/config/env';
import { API_TIMEOUT, API_HEADERS } from '@/constants/api';
import {
  clearSession,
  getActiveSessionScope,
  getSessionRefreshToken,
  getSessionToken,
  getSessionStorageKeys,
  setActiveSessionScope,
} from '@/services/auth/session';

const env = validateEnv();

const getApiBaseUrl = (): string => {
  if (
    typeof window !== 'undefined' &&
    window.location.hostname &&
    window.location.hostname.includes('onrender.com')
  ) {
    return 'https://algo-trading-backend-bqrc.onrender.com/api/v1';
  }
  if (env.VITE_API_URL && env.VITE_API_URL !== '/api/v1') {
    return env.VITE_API_URL;
  }
  return 'http://localhost:8000/api/v1';
};

const axiosInstance: AxiosInstance = axios.create({
  baseURL: getApiBaseUrl(),
  timeout: API_TIMEOUT,
  headers: API_HEADERS,
});

let isRefreshing = false;
let failedQueue: any[] = [];

const processQueue = (error: any, token: string | null = null) => {
  failedQueue.forEach(prom => {
    if (error) {
      prom.reject(error);
    } else {
      prom.resolve(token);
    }
  });
  failedQueue = [];
};

const generateSafeUUID = (): string => {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

axiosInstance.interceptors.request.use((config: InternalAxiosRequestConfig) => {
  const token = getSessionToken();
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }

  // JSON is the default for API calls, but browser file uploads must use
  // multipart/form-data with the boundary generated by the browser/Axios.
  // Leaving the global application/json header in place breaks strategy-file
  // imports with FastAPI's UploadFile endpoint.
  if (config.data instanceof FormData) {
    delete config.headers['Content-Type'];
  }

  config.headers['X-Request-ID'] = generateSafeUUID();
  return config;
});

axiosInstance.interceptors.response.use(
  (response: AxiosResponse) => response,
  async (error: AxiosError) => {
    const originalRequest = error.config as InternalAxiosRequestConfig & { _retry?: boolean };

    const isAuthRoute = originalRequest?.url?.includes('/auth/login') ||
      originalRequest?.url?.includes('/auth/register') ||
      originalRequest?.url?.includes('/auth/refresh');

    const errorMessage = ((error.response?.data as any)?.message || (error.response?.data as any)?.detail || '').toLowerCase();
    const isBrokerSessionError = errorMessage.includes('session') ||
      originalRequest?.url?.includes('/broker-data') ||
      originalRequest?.url?.includes('/broker-orders');

    if (error.response?.status === 401 && !originalRequest?._retry && !isAuthRoute && !isBrokerSessionError) {
      if (isRefreshing) {
        return new Promise((resolve, reject) => {
          failedQueue.push({ resolve, reject });
        }).then(token => {
          originalRequest.headers.Authorization = `Bearer ${token}`;
          return axiosInstance(originalRequest);
        }).catch(err => Promise.reject(err));
      }

      originalRequest._retry = true;
      isRefreshing = true;

      const scope = getActiveSessionScope();
      const refreshToken = getSessionRefreshToken(scope);
      if (!refreshToken) {
        processQueue(error);
        return Promise.reject(error);
      }

      try {
        const response = await axios.post(`${env.VITE_API_URL}/auth/refresh`, { refresh_token: refreshToken });
        const { access_token, refresh_token } = response.data.data;
        
        if (!scope) {
          return Promise.reject(new Error('No active authentication session scope'));
        }

        const keys = getSessionStorageKeys(scope);
        localStorage.setItem(keys.accessToken, access_token);
        localStorage.setItem(keys.refreshToken, refresh_token);
        setActiveSessionScope(scope);
        
        axiosInstance.defaults.headers.common['Authorization'] = `Bearer ${access_token}`;
        originalRequest.headers.Authorization = `Bearer ${access_token}`;
        
        processQueue(null, access_token);
        return axiosInstance(originalRequest);
      } catch (refreshError) {
        processQueue(refreshError, null);
        if (scope) {
          clearSession(scope);
        }
        window.location.href = '/login';
        return Promise.reject(refreshError);
      } finally {
        isRefreshing = false;
      }
    }
    
    console.error('API Error:', error);
    return Promise.reject(error);
  }
);

export default axiosInstance;
